.TH FILET 1 "2019 February 25" "" ""

.SH NAME
filet \- fucking fucking fast file fucker

.SH SYNOPSIS
.B filet
.RI [ DIR ]

.SH DESCRIPTION
filet is a blazingly fast, lightweight file manager, with a focus on a clear and easy to understand code base.
filet writes the directory you quit in into \fI/tmp/filet_dir\fR.
filet writes the file you quit on into \fI/tmp/filet_sel\fR.

.SH USAGE
.TP
j k
Move up/down

.TP
h l
Leave/enter directory

.TP
l RET
Open file using \fIFILET_OPENER\fR

.TP
~ /
Move to home/root

.TP
.
Toggle visibility of dotfiles

.TP
r
Reload dir

.TP
g G
Go to top/bottom

.TP
e
Edit using \fIEDITOR\fR

.TP
s
Spawn a \fISHELL\fR

.TP
m
Mark an item as selected

.TP
x
Delete current selection

.TP
q
Quit

.SH AUTHOR
Niclas Meyer <niclas at countingsort.com>.
For more information see https://github.com/buffet/filet.
